<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Animal extends Model
{
    protected $fillable = [
        'nombre',
        'especie_id',
        'recinto_id',
        'actividad_id',
    ];

    public function especie()
    {
        return $this->belongsTo('App\Models\Especie','especie_id');
    }

    public function recinto()
    {
        return $this->belongsTo('App\Models\Recinto','resinto_id');
    }

    public function actividad()
    {
        return $this->belongsTo('App\Models\Actividad', 'actividad_id');
    }

    public function cuidador_animals()
    {
        return $this->hasMany('App\Models\Cuidador_Animal', 'animal_id');
    }
}
